apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-3-reverseproxy
  labels:
    app: udacity-3-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-3-reverseproxy
  template:
    metadata:
      labels:
        app: udacity-3-reverseproxy
    spec:
      containers:
      - name: udacity-3-reverseproxy
        image: fjenkel/udacity-3-reverseproxy
        ports:
        - containerPort: 8080