apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-3-reverseproxy
  labels:
    app: udacity-3-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-3-reverseproxy
  template:
    metadata:
      labels:
        app: udacity-3-reverseproxy
    spec:
      containers:
      - name: udacity-3-reverseproxy
        image: fjenkel/udacity-3-reverseproxy
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /health
            port: 8080

            
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: udacity-3-reverseproxy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: udacity-3-reverseproxy
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80